export default function TermsPage() {
  return (
    <div className="max-w-3xl mx-auto py-12 px-6 prose">
      <h1 className="text-3xl font-bold mb-2">Terms of Service</h1>
      <p className="text-gray-500 mb-8">Last Updated: December 10, 2025</p>

      <div className="space-y-8 text-gray-800 leading-relaxed">
        
        <section>
          <h2 className="text-xl font-bold mb-3 text-gray-900">1. Acceptance of Terms</h2>
          <p>
            By creating an account or using Prompt My Rep ("the Service"), you agree to be bound by these Terms. 
            If you do not agree, you may not use the Service.
          </p>
        </section>

        <section>
          <h2 className="text-xl font-bold mb-3 text-gray-900">2. Description of Service</h2>
          <p>
            Prompt My Rep is an AI-powered tool designed to help users draft correspondence to elected officials. 
            The Service provides drafts based on user input and third-party data sources (news articles). 
            You acknowledge that:
          </p>
          <ul className="list-disc pl-5 mt-2 space-y-1">
            <li>We do not send messages on your behalf. You are the sole sender.</li>
            <li>We are not affiliated with any government agency or official.</li>
            <li>The Service is for personal, non-commercial civic engagement only.</li>
          </ul>
        </section>

        <section>
          <h2 className="text-xl font-bold mb-3 text-gray-900">3. AI & Accuracy Disclaimer</h2>
          <p>
            The content generated by our Service is created by Artificial Intelligence (Google Gemini). 
            AI can make mistakes, "hallucinate" facts, or misinterpret context. 
          </p>
          <p className="font-bold mt-2">
            You are responsible for reviewing, verifying, and editing all letters before sending them. 
            Prompt My Rep makes no warranties regarding the accuracy, tone, or effectiveness of the generated text.
          </p>
        </section>

        <section>
          <h2 className="text-xl font-bold mb-3 text-gray-900">4. User Conduct</h2>
          <p>You agree NOT to use the Service to:</p>
          <ul className="list-disc pl-5 mt-2 space-y-1">
            <li>Generate threats of violence, harassment, or hate speech.</li>
            <li>Impersonate others or misrepresent your identity to government officials.</li>
            <li>Spam or flood government offices with automated messages.</li>
          </ul>
          <p className="mt-2">
            We reserve the right to terminate accounts that violate these rules immediately and without notice.
          </p>
        </section>

        <section>
          <h2 className="text-xl font-bold mb-3 text-gray-900">5. Limitation of Liability</h2>
          <p className="uppercase text-xs font-bold tracking-wide text-gray-500 mb-2">READ CAREFULLY</p>
          <p>
            To the maximum extent permitted by law, Prompt My Rep and its creators shall not be liable for any 
            indirect, incidental, special, consequential, or punitive damages, including but not limited to 
            loss of data, reputation, or legal consequences resulting from your use of the generated content.
          </p>
          <p className="mt-2">
            The Service is provided "AS IS" and "AS AVAILABLE" without any warranties of any kind.
          </p>
        </section>

        <section>
          <h2 className="text-xl font-bold mb-3 text-gray-900">6. Changes to Terms</h2>
          <p>
            We may modify these terms at any time. Continued use of the Service constitutes acceptance of the new terms.
          </p>
        </section>

      </div>
    </div>
  )
}